CREATE TABLE LOGIN_USER
(	USER_ID VARCHAR2(50) NOT NULL,
	USER_NAME	VARCHAR2(50) NOT NULL,
	PASSWORD	VARCHAR2(500) NOT NULL,
	FIRST_NAME	VARCHAR2(50) NOT NULL,
	MID_NAME	VARCHAR2(10) NOT NULL,
	LAST_NAME	VARCHAR2(50) NOT NULL,
	RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT USER_ID_PK PRIMARY KEY (USER_ID)
);

CREATE TABLE ADDRESS (
  ADDRESS_ID NUMERIC(10) NOT NULL,
  STREET VARCHAR2(50) NOT NULL,
  CITY VARCHAR2(50) NOT NULL,
  ATOLL VARCHAR2(50) NOT NULL,
  COUNTRY VARCHAR2(50) NOT NULL,
  PINCODE VARCHAR2(50) NOT NULL,
	RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT ADDRESS_ID_PK PRIMARY KEY (ADDRESS_ID)
);

CREATE TABLE COMMUNICATION (
  COOMUNICATION_ID NUMERIC(10) NOT NULL,
  ADDRESS_ID NUMERIC(10) NOT NULL,
  PHONE1 VARCHAR2(50) NOT NULL,
  PHONE2 VARCHAR2(50) NOT NULL,
  FAX VARCHAR2(50) NOT NULL,
  EMAILID VARCHAR2(50) NOT NULL,
	RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT COOMUNICATION_ID_PK PRIMARY KEY (COOMUNICATION_ID),
  CONSTRAINT ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);

CREATE TABLE COMPANY_INFO
(	COMP_ID NUMERIC(10) NOT NULL,
	NAME	VARCHAR2(50) NOT NULL,
	TYPE	VARCHAR2(50),
	DESC	VARCHAR2(50),
  USER_ID NUMERIC(10) NOT NULL,
	ADDRESS_ID	NUMERIC(10) NOT NULL,
	COMMUNICATION_ID	NUMERIC(10) NOT NULL,
	RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT COMP_ID_PK PRIMARY KEY (COMP_ID),
	CONSTRAINT ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
	CONSTRAINT COMMUNICATION_ID_FK FOREIGN KEY (COMMUNICATION_ID) REFERENCES COMMUNICATION(COMMUNICATION_ID)
);

CREATE TABLE COMPANY_OPTION
(	COMP_OPTION_ID	NUMERIC(10) NOT NULL,
	COMP_ID	NUMERIC(10) NOT NULL,
	REF_KEY	VARCHAR2(50) NOT NULL,
	REF_TEXT	VARCHAR2(50) NOT NULL,
	REF_VALUE	VARCHAR2(50) NOT NULL,
	CONSTRAINT COMP_OPTION_ID_PK PRIMARY KEY (COMP_OPTION_ID),
	CONSTRAINT COMP_ID_FK FOREIGN KEY (COMP_ID) REFERENCES COMPANY_INFO(COMP_ID)
);

CREATE TABLE SUPPLIER
(	SUPPLIER_ID	NUMERIC(10) NOT NULL,
	NAME	VARCHAR2(50) NOT NULL,
	GROUP	VARCHAR2(50) NOT NULL,
	TYPE	VARCHAR2(50) NOT NULL,
	PARENT_COMP_ID	NUMERIC(10) NOT NULL,
	COMP_ID	NUMERIC(10) NOT NULL,
	ADDRESS_ID	NUMERIC(10) NOT NULL,
	COMMUNICATION_ID	NUMERIC(10) NOT NULL,
	RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT SUPPLIER_ID_PK PRIMARY KEY (SUPPLIER_ID),
	CONSTRAINT COMP_ID_FK FOREIGN KEY (COMP_ID) REFERENCES COMPANY_INFO(COMP_ID),
	CONSTRAINT ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
	CONSTRAINT COMMUNICATION_ID_FK FOREIGN KEY (COMMUNICATION_ID) REFERENCES COMMUNICATION(COMMUNICATION_ID)
);

CREATE TABLE PRODUCT_GROUP (
  GROUP_ID	NUMERIC(10) NOT NULL,
  GROUP_NAME VARCHAR2(50) NOT NULL,
  SHORT_NAME VARCHAR2(50) NOT NULL,
  STOCK_VALUVATION VARCHAR2(50) NOT NULL,
  RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT GROUP_ID_PK PRIMARY KEY (GROUP_ID)
);

CREATE TABLE PRODUCT_SUBGROUP (
  SUBGROUP_ID NUMERIC(10) NOT NULL,
  GROUP_ID NUMERIC(10) NOT NULL,
  SUBGROUP_NAME VARCHAR2(50) NOT NULL,
  SUBGROUP_SHORT_NAME VARCHAR2(50) NOT NULL,
  RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT SUBGROUP_IDD_PK PRIMARY KEY (SUBGROUP_ID)
);

CREATE TABLE IMPORT_STAF (
  STAFF_ID NUMERIC(10) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  CURRENCY VARCHAR2(50) NOT NULL,
  CRIDIT_LIMIT NUMERIC(10) NOT NULL,
  DATE_OF_JOIN DATE NOT NULL,
  DATE_OF_RELIEVING DATE NOT NULL,
  IS_TERMINATE VARCHAR2(1) NOT NULL,
  TERMINATE_REASON VARCHAR2(50) NOT NULL,
  IS_ACTIVE VARCHAR2(1) NOT NULL,
  IS_DEFAULT_PAYROL VARCHAR2(1) NOT NULL,
  ADDRESS_ID NUMERIC(10) NOT NULL,
  COMMUNICATION_ID NUMERIC(10) NOT NULL,
  COMPANY_ID NUMERIC(10) NOT NULL,
  BANK_ID NUMERIC(10) NOT NULL,
  RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT STAFF_ID_PK PRIMARY KEY (STAFF_ID),
	CONSTRAINT ADDRESS_ID_FK FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID),
	CONSTRAINT COMMUNICATION_ID_FK FOREIGN KEY (COMMUNICATION_ID) REFERENCES COMMUNICATION(COMMUNICATION_ID),
  CONSTRAINT COMP_ID_FK FOREIGN KEY (COMP_ID) REFERENCES COMPANY_INFO(COMP_ID)
);


CREATE TABLE PRODUCTS (
  PRODUCT_ID NUMERIC(10) NOT NULL,
  NAME VARCHAR2(50) NOT NULL,
  PRINT_NAME VARCHAR2(50) NOT NULL,
  TYPE VARCHAR2(50) NOT NULL,
  SUBGROUP_ID NUMERIC(10) NOT NULL,
  STACK_EVALUVATION VARCHAR2(50) NOT NULL,
  REORDER_LEVEL VARCHAR2(50) NOT NULL,
  MIN_LEVEL NUMERIC(10) NOT NULL,
  MAX_LEVEL NUMERIC(10) NOT NULL,
  UNIT VARCHAR2(50) NOT NULL,
  TAX_TYPE VARCHAR2(50) NOT NULL,
  CUSTOM_CODE VARCHAR2(50) NOT NULL,
  ROYALITY_PERCENTAGE VARCHAR2(50) NOT NULL,
  VENDOR_ID VARCHAR2(50) NOT NULL,
  IS_RATE_EDITABLE VARCHAR2(1) NOT NULL,
  IS_ACTIVE VARCHAR2(1) NOT NULL,
  IS_COCKTAIL VARCHAR2(1) NOT NULL,
  IS_EXPAIRY_TRACKING VARCHAR2(1) NOT NULL,
  RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT PRODUCT_ID_PK PRIMARY KEY (PRODUCT_ID),
	CONSTRAINT SUBGROUP_ID_FK FOREIGN KEY (SUBGROUP_ID) REFERENCES PRODUCT_SUBGROUP(SUBGROUP_ID)
);

CREATE TABLE PRICE_LIST (
  PRICE_ID NUMERIC(10) NOT NULL,
  PRODUCT_ID NUMERIC(10) NOT NULL,
  UOM VARCHAR2(50) NOT NULL,
  PRICE_LEVEL VARCHAR2(50) NOT NULL,
  EFFECTIVE_FROM VARCHAR2(50) NOT NULL,
  CURRENCY VARCHAR2(50) NOT NULL,
  RATE VARCHAR2(50) NOT NULL,
  COST_PRICE VARCHAR2(50) NOT NULL,
  RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT PRICE_ID_PK PRIMARY KEY (PRICE_ID),
  CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE PURCHES_ORDERS(
  ORDER_ID NUMERIC(10) NOT NULL,
  BOOK_TYPE VARCHAR2(50) NOT NULL,
  REF_NUMB VARCHAR2(50) NOT NULL,
  ENTRY_DT DATE NOT NULL,
  BILL_DT DATE NOT NULL,
  MODE VARCHAR2(50) NOT NULL,
  ISSUE_TYPE VARCHAR2(50) NOT NULL,
  SUPPLIER_ID NUMERIC(10) NOT NULL,
  IS_CLOSED VARCHAR2(1) NOT NULL,
  CURRENCY VARCHAR2(50) NOT NULL,
  DELEVERY_DT DATE,
  IS_RETURN VARCHAR2(1) NOT NULL,
  RETURN_DT DATE,
  RCD_CRD_ID	VARCHAR2(50) NOT NULL,
	RCD_UPD_ID	VARCHAR2(50) NOT NULL,
	RCD_CRD_DT	DATE NOT NULL,
	RCD_UPD_DT	DATE NOT NULL,
	CONSTRAINT ORDER_ID_PK PRIMARY KEY (ORDER_ID),
  CONSTRAINT SUPPLIER_ID_FK FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID)
);

CREATE TABLE PUCHES_PRODUCTS(
  PURCHES_ID NUMERIC(10) NOT NULL,
  ORDER_ID NUMERIC(10) NOT NULL,
  PRODUCT_ID NUMERIC(10) NOT NULL,
  UOM VARCHAR2(50) NOT NULL,
  IS_RETURN VARCHAR2(1) NOT NULL,
  QUANDITY VARCHAR2(50) NOT NULL,
  RATE VARCHAR2(50) NOT NULL,
  AMOUNT VARCHAR2(50) NOT NULL,
  GST VARCHAR2(50) NOT NULL,
  COST_PRICE VARCHAR2(50) NOT NULL,
	CONSTRAINT PURCHES_ID_PK PRIMARY KEY (PURCHES_ID),
  CONSTRAINT ORDER_ID_FK FOREIGN KEY (ORDER_ID) REFERENCES PURCHES_ORDERS(ORDER_ID),
  CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);

CREATE TABLE SALES_DIRECT_BILL (
  SALES_BILL_ID NUMERIC(10) NOT NULL,
  BOOK_TYPE VARCHAR2(50) NOT NULL,
  BILL_NO VARCHAR2(50) NOT NULL,
  BILL_DT DATE,
  MODE  VARCHAR2(50) NOT NULL,
  DUE_DT DATE,
  STAFF  VARCHAR2(50) NOT NULL,
  TINN_NO  VARCHAR2(50) NOT NULL,
  CURRENCY  VARCHAR2(50) NOT NULL,
  IS_RETURN  VARCHAR2(1) NOT NULL,
  RETURN_DT DATE,
	CONSTRAINT SALES_BILL_ID_PK PRIMARY KEY (SALES_BILL_ID)
)

CREATE TABLE SALES_PRODUCT (
  SALES_PRODUCT_ID NUMERIC(10) NOT NULL,
  SALES_BILL_ID  NUMERIC(10) NOT NULL,
  PRODUCT_ID NUMERIC(10) NOT NULL,
  BARCODE VARCHAR2(50) NOT NULL,
  QUANDITY NUMERIC(10) NOT NULL,
  RATE VARCHAR2(50) NOT NULL,
  AMOUNT VARCHAR2(50) NOT NULL,
  GST VARCHAR2(50) NOT NULL,
  IS_RETURN VARCHAR2(1) NOT NULL,
  CONSTRAINT SALES_BILL_ID_PK PRIMARY KEY (SALES_BILL_ID),
  CONSTRAINT SALES_BILL_ID_FK FOREIGN KEY (SALES_BILL_ID) REFERENCES SALES_DIRECT_BILL(SALES_BILL_ID),
  CONSTRAINT PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)
