/*for sequence id each module*/
INSERT INTO SEQ_KEY(ID, NAME, VALUE) VALUES(3, 'MY_LOCATION_SEQ', 10000);
INSERT INTO SEQ_KEY(ID, NAME, VALUE) VALUES(4, 'MOVIE_INFO_SEQ', 20000);
INSERT INTO SEQ_KEY(ID, NAME, VALUE) VALUES(5, 'MOVIE_IMAGES_SEQ', 40000);
INSERT INTO SEQ_KEY(ID, NAME, VALUE) VALUES(6, 'LOGIN_USER_SEQ', 60000);
INSERT INTO SEQ_KEY(ID, NAME, VALUE) VALUES(7, 'BLOG_INFO_SEQ', 70000);
INSERT INTO SEQ_KEY(ID, NAME, VALUE) VALUES(8, 'BLOG_REVIEW_SEQ', 90000);
/*Insert all contry,state, district, area*/
INSERT INTO COUNTRY (ID, COUNTRY) VALUES(100, 'INDIA');
INSERT INTO STATE (ID, STATE, COUNTRY_ID ) VALUES(1000, 'TAMILNADU', 100);
INSERT INTO DISCTRICT (ID, DISCTRICT, STATE_ID ) VALUES(2000, 'NAMAKKAL', 1000);
INSERT INTO AREA (ID, NAME, DISTRICT_ID ) VALUES(5000, 'THOTTYAM', 2000);
INSERT INTO AREA (ID, NAME, DISTRICT_ID ) VALUES(5001, 'VALAYAPATTI', 2001);

INSERT INTO DISCTRICT (ID, DISCTRICT, STATE_ID ) SELECT MAX(ID)+1, 'CHENNAI', 1000  FROM DISCTRICT;
INSERT INTO AREA (ID, NAME, DISTRICT_ID ) SELECT MAX(ID)+1, 'THAMBARAM',(SELECT ID FROM DISCTRICT WHERE DISCTRICT = 'CHENNAI') FROM AREA ;
INSERT INTO AREA (ID, NAME, DISTRICT_ID ) SELECT MAX(ID)+1, 'T_NAGAR',(SELECT ID FROM DISCTRICT WHERE DISCTRICT = 'CHENNAI') FROM AREA ;


