

http://www.lanexa.net/2011/08/create-a-mysql-database-username-password-and-permissions-from-the-command-line/

SHOW DATABASES;

CREATE USER POC;

GRANT ALL ON THARCLICK.* TO 'poc'@'mspire.in' identified by 'babu@Selvam10';

GRANT SELECT, INSERT, DELETE, UPDATE ON 'poc'@'mspire.in' identified by 'babu@Selvam10';


CREATE TABLE SEQ_KEY ( 
ID INT(10),
NAME VARCHAR(40),
VALUE INT(10), 
PRIMARY KEY (ID)
);

CREATE TABLE LOGIN_USERS ( 
PHONE_NO VARCHAR(60),
FIRST_NAME VARCHAR(40) NOT NULL,
LAST_NAME VARCHAR(40) NOT NULL,
EMAIL VARCHAR(60),
RCD_CRD_ID VARCHAR(15) NOT NULL,
RCD_CRD_DT DATE NOT NULL,
LST_UPDT_ID VARCHAR(15) NOT NULL,
LST_UPDT_DT DATE NOT NULL,
PRIMARY KEY (PHONE_NO)
);

CREATE TABLE MOVIE_INFO (
ID INT(10) NOT NULL,
MOVIE_NAME VARCHAR(300) NOT NULL,
MOVIE_RELEASE_DATE DATE,
MOVIE_LANGUAGE VARCHAR(30) NOT NULL,
MOVIE_ORGIN VARCHAR(100) NOT NULL,
MOVIE_ORGIN_VARIANT VARCHAR(100) NOT NULL,
MOVIE_GENRES VARCHAR(300) NOT NULL,
MOVIE_SYNOPSIS VARCHAR(1000) NOT NULL,
MOVIE_IS_3D VARCHAR(1) NOT NULL,
MOVIE_TEAM_ROLE_IDS VARCHAR(100) NOT NULL,
MOVIE_TRAILER_LINK VARCHAR(300),
MOVIE_TEASER_LINK VARCHAR(300),
MOVIE_RATING INT(1), 
MOVIE_CERTIF VARCHAR(5) NOT NULL,
MOVIE_RUN_TIME VARCHAR(40) NOT NULL,
RCD_CRD_ID VARCHAR(15) NOT NULL,
RCD_CRD_DT DATE NOT NULL,
LST_UPDT_ID VARCHAR(15) NOT NULL,
LST_UPDT_DT DATE NOT NULL,
PRIMARY KEY (ID)
);



CREATE TABLE MOVIE_IMAGES (
ID INT(10) NOT NULL,
MOVIE_INFO_ID INT(10) NOT NULL,
MOV_IMG_PATH VARCHAR(300) NOT NULL,
MOV_IMG_VIEW_TYPE VARCHAR(100) NOT NULL,
RCD_CRD_ID VARCHAR(15) NOT NULL,
RCD_CRD_DT DATE NOT NULL,
LST_UPDT_ID VARCHAR(15) NOT NULL,
LST_UPDT_DT DATE NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (MOVIE_INFO_ID) REFERENCES MOVIE_INFO(ID)
);

CREATE TABLE COUNTRY (
ID INT(10) NOT NULL,
COUNTRY VARCHAR(100) NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE STATE(
ID INT(10) NOT NULL,
STATE VARCHAR(100) NOT NULL,
COUNTRY_ID INT(10) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY(ID)
);

CREATE TABLE DISCTRICT (
ID INT(10) NOT NULL,
DISCTRICT VARCHAR(100) NOT NULL,
STATE_ID INT(10) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (STATE_ID) REFERENCES STATE(ID)
);

CREATE TABLE AREA(
ID INT(10) NOT NULL,
NAME VARCHAR(100) NOT NULL,
DISTRICT_ID INT(10) NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (DISTRICT_ID) REFERENCES DISCTRICT(ID)
);

CREATE TABLE MY_LOCATION(
ID INT(10) NOT NULL,
USR_IP_ADDR VARCHAR(20) NOT NULL,
USR_MAC_ADDRESS VARCHAR(50) NOT NULL,
DISCTRICT_ID INT(10) NOT NULL,
AREA_ID INT(10) NOT NULL,
RCD_CRD_ID VARCHAR(15) NOT NULL,
RCD_CRD_DT DATE NOT NULL,
LST_UPDT_ID VARCHAR(15) NOT NULL,
LST_UPDT_DT DATE NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (DISCTRICT_ID) REFERENCES DISCTRICT(ID),
FOREIGN KEY (AREA_ID) REFERENCES AREA(ID)
);

CREATE TABLE BLOG_INFO (
ID INT(10) NOT NULL,
BLOG_ARTIC_HEADING VARCHAR(500) NOT NULL,
BLOG_ARTIC_TYPE VARCHAR(10) NOT NULL,
BLOG_ARTIC_DESC VARCHAR(1000),
BLOG_LIKE_COUNT INT(10) ,
BLOG_UNLIKE_COUNT INT(10),
MOVIE_INFO_ID INT(10) NOT NULL,
BLOG_ROLE_ID INT(10),
BLOG_IMAGES_PATH  VARCHAR(50),
RCD_CRD_ID VARCHAR(15) NOT NULL,
RCD_CRD_DT DATE NOT NULL,
LST_UPDT_ID VARCHAR(15) NOT NULL,
LST_UPDT_DT DATE NOT NULL,
PRIMARY KEY (ID),
CONSTRAINT FOREIGN KEY (MOVIE_INFO_ID) REFERENCES MOVIE_INFO(ID)
);


CREATE TABLE BLOG_REVIEWS(
ID INT(10) NOT NULL,
BLOG_COMMENTS VARCHAR(1000),
BLOG_CMNT_LIK_CNT INT(10) ,
BLOG_CMNT_UNLIK_CNT INT(10) ,
BLOG_IS_REPORT_ABUSE VARCHAR(1),
BLOG_INFO_ID INT(10) NOT NULL,
RCD_CRD_ID VARCHAR(15) NOT NULL,
RCD_CRD_DT DATE NOT NULL,
LST_UPDT_ID VARCHAR(15) NOT NULL,
LST_UPDT_DT DATE NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (BLOG_INFO_ID) REFERENCES BLOG_INFO(ID)
);


CREATE TABLE BLOG_VIDEOS (
ID INT(10) NOT NULL,
BLOG_VIDEO_LINK VARCHAR(100) NOT NULL,
BLOG_INFO_ID INT(10) NOT NULL,
RCD_CRD_ID VARCHAR(15) NOT NULL,
RCD_CRD_DT DATE NOT NULL,
LST_UPDT_ID VARCHAR(15) NOT NULL,
LST_UPDT_DT DATE NOT NULL,
PRIMARY KEY (ID),
FOREIGN KEY (BLOG_INFO_ID) REFERENCES BLOG_INFO(ID)
);


CREATE TABLE LOGIN_USERS ( 
ID INT(10) NOT NULL,
FIRST_NAME VARCHAR(40) NOT NULL,
LAST_NAME VARCHAR(40) NOT NULL,
EMAIL VARCHAR(60),
PHONE_NO VARCHAR(60),
RCD_CRD_ID VARCHAR(15) NOT NULL,
RCD_CRD_DT DATE NOT NULL,
LST_UPDT_ID VARCHAR(15) NOT NULL,
LST_UPDT_DT DATE NOT NULL,
PRIMARY KEY (ID)
);
